name: 'vuln-diff-action: phase1 (analysis)'
description: 'Phase 1 — Analysis: SBOM + Grype scan y meta (sin normalización/diff/render).'
branding:
  color: 'purple'
  icon: 'shield'
inputs:
  base_ref:
    description: 'Ref base (por ejemplo origin/develop o un SHA)'
    required: true
  head_ref:
    description: 'Ref head (por ejemplo origin/feature-x o un SHA)'
    required: true
  path:
    description: 'Subdirectorio a analizar (raíz del módulo/proyecto).'
    required: false
    default: '.'
outputs:
  base_sha:
    description: 'SHA resuelto de base_ref'
  head_sha:
    description: 'SHA resuelto de head_ref'
runs:
  using: 'node20'
  main: 'index.js'
