name: "Vulnerability Diff Action"
description: "Compare vulnerabilities between two refs using Syft+Grype (enhanced HTML/PDF reporting, PR comment, Slack)"
author: "sec-open"
branding:
  color: "purple"
  icon: "shield"

inputs:
  base_ref:
    description: "Base ref (branch, tag, or commit SHA)"
    required: true
  head_ref:
    description: "Head ref (branch, tag, or commit SHA)"
    required: true
  path:
    description: "Path to scan (relative to repo root)"
    required: false
    default: "."
  build_command:
    description: "Optional build command to run in each worktree before SBOM (e.g., mvn -q -DskipTests package)"
    required: false
    default: ""
  min_severity:
    description: "Minimum severity to include (LOW, MEDIUM, HIGH, CRITICAL)"
    required: false
    default: "LOW"
  write_summary:
    description: "Write GitHub job summary"
    required: false
    default: "true"
  upload_artifact:
    description: "Upload artifacts (SBOMs, scans, diff, reports)"
    required: false
    default: "true"
  artifact_name:
    description: "Artifact name"
    required: false
    default: "vuln-diff-artifacts"
  graph_max_nodes:
    description: "Max nodes for dependency graphs"
    required: false
    default: "150"

  # Reporting v2 options
  report_html:
    description: "Generate HTML report (besides PDF)"
    required: false
    default: "true"
  report_pdf:
    description: "Generate PDF report"
    required: false
    default: "true"
  title_logo_url:
    description: "Optional logo URL for report cover"
    required: false
    default: ""

  # PR comment
  pr_comment:
    description: "Upsert a reusable PR comment"
    required: false
    default: "false"
  pr_comment_marker:
    description: "Hidden marker used to find/update the PR comment"
    required: false
    default: "<!-- vuln-diff-action:comment -->"
  github_token:
    description: "GitHub token (required for PR comment)"
    required: false
    default: ""

  # Slack
  slack_webhook_url:
    description: "Slack Incoming Webhook URL (secret)"
    required: false
    default: ""
  slack_channel:
    description: "Optional Slack channel override (may be ignored by your webhook)"
    required: false
    default: ""

runs:
  using: "node20"
  main: "dist/index.js"
