name: 'vuln-diff-action: phase1 (analysis)'
description: 'Phase 1 — Analysis: SBOM + Grype + meta (sin normalización/diff/render).'
branding:
  color: 'purple'
  icon: 'shield'
inputs:
  base_ref:
    description: 'Ref base (p.ej. origin/develop o un SHA)'
    required: true
  head_ref:
    description: 'Ref head (p.ej. origin/feature-x o un SHA)'
    required: true
  path:
    description: 'Subdirectorio a analizar'
    required: false
    default: '.'
outputs:
  base_sha:
    description: 'SHA resuelto de base_ref'
  head_sha:
    description: 'SHA resuelto de head_ref'
runs:
  using: 'node20'
  main: '.bundle/index.js'
