name: "Vulnerability Diff (Syft+Grype)"
description: "Compare vulnerabilities between two refs (base/head) and output a Markdown table, JSON diff, and upload artifacts"
author: "sec-open"
runs:
  using: "node20"
  main: "dist/index.js"

inputs:
  base_ref:
    description: "Base ref/branch/sha to compare against (e.g., main)"
    required: true
  head_ref:
    description: "Head ref/branch/sha to compare"
    required: true
  path:
    description: "Subdirectory to scan (monorepo). Default: repo root"
    required: false
    default: "."
  build_command:
    description: "Optional build command before scanning"
    required: false
    default: ""
  min_severity:
    description: "Minimum severity to report: LOW|MEDIUM|HIGH|CRITICAL (inclusive)"
    required: false
    default: "LOW"
  write_summary:
    description: "Write Markdown table to GITHUB_STEP_SUMMARY"
    required: false
    default: "true"
  upload_artifact:
    description: "Upload SBOMs, grype outputs and a full report as artifact"
    required: false
    default: "true"
  artifact_name:
    description: "Artifact name"
    required: false
    default: "vuln-diff-artifacts"
  graph_max_nodes:
    description: "Max nodes to include in the Mermaid dependency graph"
    required: false
    default: "150"
  report_pdf:
    description: "Also render report.pdf using Puppeteer"
    required: false
    default: "false"

outputs:
  new_count:
    description: "Number of NEW vulnerabilities introduced by head over base"
  removed_count:
    description: "Number of vulnerabilities REMOVED by head vs base"
  unchanged_count:
    description: "Number of unchanged vulnerabilities"
  diff_markdown_table:
    description: "Markdown table with Severity | VulnerabilityID | package:version | branches"
  diff_json:
    description: "JSON diff payload"
  base_sha:
    description: "Resolved base commit SHA"
  head_sha:
    description: "Resolved head commit SHA"
  base_input:
    description: "Raw base input ref"
  head_input:
    description: "Raw head input ref"
