name: "Vulnerability Diff Action"
description: "Compare vulnerabilities between two refs using Syft+Grype → base.json, head.json, diff.json → Markdown/HTML/PDF renderers"
author: "sec-open"
runs:
  using: "node20"
  main: "dist/index.js"

inputs:
  base_ref:
    description: "Base branch/tag/SHA"
    required: true
  head_ref:
    description: "Head branch/tag/SHA"
    required: true
  path:
    description: "Directory to scan"
    required: false
    default: "."
  build_command:
    description: "Optional build command (e.g. mvn -q -DskipTests package)"
    required: false
    default: ""
  min_severity:
    description: "LOW|MEDIUM|HIGH|CRITICAL"
    required: false
    default: "LOW"
  write_summary:
    description: "Write GitHub job summary (markdown)"
    required: false
    default: "true"
  report_html:
    description: "Generate interactive HTML report"
    required: false
    default: "true"
  report_pdf:
    description: "Generate PDF (cover + main + landscape)"
    required: false
    default: "true"
  upload_artifact:
    description: "Upload artifacts (JSON/HTML/PDF)"
    required: false
    default: "true"
  artifact_name:
    description: "Artifact name"
    required: false
    default: "vulnerability-diff"
  title_logo_url:
    description: "Optional logo URL for cover/header/footer"
    required: false
    default: ""
  graph_max_nodes:
    description: "Max graph nodes (mermaid)"
    required: false
    default: "150"
  pr_comment:
    description: "Create/update PR comment with NEW vulns"
    required: false
    default: "false"
  pr_comment_marker:
    description: "Hidden marker for updatable PR comment"
    required: false
    default: "<!-- vuln-diff-action:comment -->"
  github_token:
    description: "GitHub token for PR comment"
    required: false
    default: ""
  slack_webhook_url:
    description: "Optional Slack incoming webhook"
    required: false
    default: ""

outputs:
  new_count:
    description: "Number of NEW vulns"
  removed_count:
    description: "Number of REMOVED vulns"
  unchanged_count:
    description: "Number of UNCHANGED vulns"
