// ...existing code...
if (isJavaScriptProject(repoPath)) {
    return { type: 'javascript', sbomFormat: 'cyclonedx-json', scanners: ['npm-audit', 'grype-sbom', 'trivy-sbom', 'osv-sbom', 'retire'] };
}
// ...existing code...
